spring:
#  application:
#    name: payer-daily
  config:
    import: optional:configserver:http://localhost:8445/
  profiles:
    active: dev

#server:
#  port: 8442

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      getTransactionBreaker1:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      getTransactionBreaker2:
        registerHealthIndicator: true
        maxRetryAttempts: 5
        waitDuration: 10s

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    serverUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true

