spring:
  application:
    name: payment-process
  config:
    import: optional:configserver:http://localhost:8445/

#server:
#  port: 8443

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    serverUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true

